services:
  databse:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_USERNAME=secret
    ports:
      - "27017:27017"
  backend:
    image: agile-back-end
    build: ./back-end
    env_file:
      - ./back-end/.env
    ports:
      - "5002:5002"
  frontend:
    image: agile-front-end
    build: ./front-end
    env_file:
      - ./front-end/.env
    ports:
      - "7002:7002"
